### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by SerkanSipahi** [Polymer/layout#4]
It would be nice if we have any examples

**Comment by ebidel** [comment]
This doc is still relevant:
https://www.polymer-project.org/docs/polymer/layout-attrs.html

Not sure if the plan is for polymer 0.8 to still  import these for you.

**Comment by SerkanSipahi** [comment]
@ebidel : I found this repository in https://github.com/Polymer/. The first thing I thought was awesome approach with css-flexbox to build a layout. If possible i would like to import the information from https://www.polymer-project.org/docs/polymer/layout-attrs.html to here( README.md ). Polymer/Layout has big potential :)

**Comment by ebidel** [comment]
We've tried to steer away from having docs in multiple places. Things were getting stale.
When a page exists on polymer-project.org, we should definitely have pointers from the repo/README to the site page.That will help anyone discovering content through github.

**Comment by SerkanSipahi** [comment]
Your are right. See: https://github.com/Polymer/layout/pull/6 "pull request"

**Comment by ssorallen** [comment]
Closing this since this repo now points to its documentation on the Polymer website, which has demos.
